# Generated by Django 4.2.20 on 2025-07-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_perfil", models.URLField(max_length=255)),
                ("divulgacao_cantor", models.URLField(max_length=255)),
                ("divulgacao_show", models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TipoShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_show", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("foto_show", models.URLField(max_length=100)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="paginas.local"
                    ),
                ),
                (
                    "tipo_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.tiposhow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfilCantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_artistico", models.CharField(max_length=100)),
                ("genero_musical", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("foto", models.URLField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_cantor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
