# Generated by Django 4.2.20 on 2025-09-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_show_cantor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="show",
            options={"ordering": ["data"]},
        ),
        migrations.AlterField(
            model_name="perfilcantor",
            name="descricao",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="perfilcantor",
            name="foto",
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="perfilcantor",
            name="genero_musical",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
