# Generated by Django 4.2.20 on 2025-05-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_perfil", models.URLField(max_length=255)),
                ("divulgacao_cantor", models.URLField(max_length=255)),
                ("divulgacao_show", models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PerfilCantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_artistico", models.CharField(max_length=100)),
                ("genero_musical", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("foto", models.URLField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("foto_show", models.URLField(max_length=100)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="paginas.local"
                    ),
                ),
                (
                    "tipo_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.tiposhow",
                    ),
                ),
            ],
        ),
    ]
