# Generated by Django 4.2.20 on 2025-05-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0002_midia_perfilcantor_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="nome",
            field=models.CharField(default="kkkkk", max_length=100),
            preserve_default=False,
        ),
    ]
