# Generated by Django 4.2.20 on 2025-07-28 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paginas", "0003_show_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilcantor",
            name="usuario",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_cantor",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
